// Offline catalogue used when TMDB_API_KEY is missing or TMDB is unreachable.
// Ids match TMDB so watchlist entries keep working once a key is added.
export type FallbackMovie = {
  id: number;
  title: string;
  year: number;
  rating: number;
  votes: number;
  runtime: number;
  genres: number[];
  tagline: string;
  overview: string;
  cast: [string, string][];
};

export const FALLBACK_MOVIES: FallbackMovie[] = [
  { id: 181812, title: "Star Wars: The Rise of Skywalker", year: 2019, rating: 6.3, votes: 10200, runtime: 142, genres: [12, 28, 878], tagline: "Every generation has a legend.", overview: "The surviving Resistance faces the First Order once more as the conflict between Jedi and Sith reaches its end.", cast: [["Daisy Ridley", "Rey"], ["Adam Driver", "Kylo Ren"], ["John Boyega", "Finn"], ["Oscar Isaac", "Poe Dameron"]] },
  { id: 324857, title: "Spider-Man: Into the Spider-Verse", year: 2018, rating: 8.4, votes: 15800, runtime: 117, genres: [16, 28, 12, 878], tagline: "More than one wears the mask.", overview: "Teenager Miles Morales becomes Spider-Man and crosses paths with spider-people from other dimensions.", cast: [["Shameik Moore", "Miles Morales"], ["Hailee Steinfeld", "Gwen Stacy"], ["Jake Johnson", "Peter B. Parker"], ["Mahershala Ali", "Aaron Davis"]] },
  { id: 293167, title: "Kong: Skull Island", year: 2017, rating: 6.5, votes: 11000, runtime: 118, genres: [28, 12, 14], tagline: "All hail the king.", overview: "A crew sent to map an uncharted island is attacked by a colossal ape and must survive the monsters beneath it.", cast: [["Tom Hiddleston", "James Conrad"], ["Brie Larson", "Mason Weaver"], ["Samuel L. Jackson", "Preston Packard"], ["John Goodman", "Bill Randa"]] },
  { id: 374720, title: "Dunkirk", year: 2017, rating: 7.5, votes: 16500, runtime: 106, genres: [10752, 28, 18], tagline: "When 400,000 men couldn't get home, home came for them.", overview: "Allied soldiers surrounded on a French beach wait for rescue by land, sea and air.", cast: [["Fionn Whitehead", "Tommy"], ["Tom Hardy", "Farrier"], ["Mark Rylance", "Mr. Dawson"], ["Kenneth Branagh", "Commander Bolton"]] },
  { id: 286217, title: "The Martian", year: 2015, rating: 7.7, votes: 20500, runtime: 144, genres: [18, 12, 878], tagline: "Bring him home.", overview: "An astronaut left for dead on Mars uses science and stubbornness to survive until rescue.", cast: [["Matt Damon", "Mark Watney"], ["Jessica Chastain", "Melissa Lewis"], ["Chiwetel Ejiofor", "Vincent Kapoor"], ["Jeff Daniels", "Teddy Sanders"]] },
  { id: 299534, title: "Avengers: Endgame", year: 2019, rating: 8.2, votes: 25000, runtime: 181, genres: [12, 878, 28], tagline: "Avenge the fallen.", overview: "The remaining Avengers regroup for one last attempt to undo the snap that wiped out half of all life.", cast: [["Robert Downey Jr.", "Tony Stark"], ["Chris Evans", "Steve Rogers"], ["Scarlett Johansson", "Natasha Romanoff"], ["Mark Ruffalo", "Bruce Banner"]] },
  { id: 603692, title: "John Wick: Chapter 4", year: 2023, rating: 7.7, votes: 6500, runtime: 170, genres: [28, 53, 80], tagline: "No way back, one way out.", overview: "John Wick takes on the High Table across continents to win his freedom.", cast: [["Keanu Reeves", "John Wick"], ["Donnie Yen", "Caine"], ["Bill Skarsgård", "Marquis"], ["Ian McShane", "Winston"]] },
  { id: 940721, title: "Godzilla Minus One", year: 2023, rating: 7.6, votes: 2300, runtime: 125, genres: [878, 27, 28], tagline: "Postwar Japan. From zero to minus.", overview: "In the ruins of postwar Japan, a former kamikaze pilot faces a monster that threatens everything left.", cast: [["Ryunosuke Kamiki", "Koichi Shikishima"], ["Minami Hamabe", "Noriko Oishi"], ["Yuki Yamada", "Shiro Mizushima"]] },
  { id: 27205, title: "Inception", year: 2010, rating: 8.4, votes: 36000, runtime: 148, genres: [28, 878, 12], tagline: "Your mind is the scene of the crime.", overview: "A thief who steals secrets through dreams is hired to plant an idea instead.", cast: [["Leonardo DiCaprio", "Cobb"], ["Joseph Gordon-Levitt", "Arthur"], ["Elliot Page", "Ariadne"], ["Tom Hardy", "Eames"]] },
  { id: 157336, title: "Interstellar", year: 2014, rating: 8.4, votes: 34000, runtime: 169, genres: [12, 18, 878], tagline: "Mankind was born on Earth. It was never meant to die here.", overview: "Explorers travel through a wormhole to find humanity a new home as Earth fails.", cast: [["Matthew McConaughey", "Cooper"], ["Anne Hathaway", "Brand"], ["Jessica Chastain", "Murph"], ["Michael Caine", "Professor Brand"]] },
  { id: 155, title: "The Dark Knight", year: 2008, rating: 8.5, votes: 32000, runtime: 152, genres: [18, 28, 80, 53], tagline: "Why so serious?", overview: "Batman faces the Joker, a criminal who wants to prove anyone can be pushed into chaos.", cast: [["Christian Bale", "Bruce Wayne"], ["Heath Ledger", "Joker"], ["Aaron Eckhart", "Harvey Dent"], ["Gary Oldman", "Jim Gordon"]] },
  { id: 603, title: "The Matrix", year: 1999, rating: 8.2, votes: 25000, runtime: 136, genres: [28, 878], tagline: "Welcome to the real world.", overview: "A hacker learns his reality is a simulation and joins the rebellion against its machine makers.", cast: [["Keanu Reeves", "Neo"], ["Laurence Fishburne", "Morpheus"], ["Carrie-Anne Moss", "Trinity"], ["Hugo Weaving", "Agent Smith"]] },
  { id: 680, title: "Pulp Fiction", year: 1994, rating: 8.5, votes: 27000, runtime: 154, genres: [53, 80], tagline: "Just because you are a character doesn't mean you have character.", overview: "Hitmen, a boxer and a gangster's wife collide in interlocking Los Angeles crime stories.", cast: [["John Travolta", "Vincent Vega"], ["Samuel L. Jackson", "Jules Winnfield"], ["Uma Thurman", "Mia Wallace"], ["Bruce Willis", "Butch"]] },
  { id: 13, title: "Forrest Gump", year: 1994, rating: 8.5, votes: 26000, runtime: 142, genres: [35, 18, 10749], tagline: "The world will never be the same once you've seen it through the eyes of Forrest Gump.", overview: "A kind man with a low IQ drifts through decades of American history and never stops loving Jenny.", cast: [["Tom Hanks", "Forrest Gump"], ["Robin Wright", "Jenny"], ["Gary Sinise", "Lt. Dan"], ["Sally Field", "Mrs. Gump"]] },
  { id: 129, title: "Spirited Away", year: 2001, rating: 8.5, votes: 16000, runtime: 125, genres: [16, 10751, 14], tagline: "Nothing that happens is ever forgotten.", overview: "A girl trapped in a spirit world must work in a bathhouse to free herself and her parents.", cast: [["Rumi Hiiragi", "Chihiro"], ["Miyu Irino", "Haku"], ["Mari Natsuki", "Yubaba"]] },
  { id: 496243, title: "Parasite", year: 2019, rating: 8.5, votes: 18000, runtime: 133, genres: [35, 53, 18], tagline: "Act like you own the place.", overview: "A poor family schemes its way into a wealthy household until a hidden secret surfaces.", cast: [["Song Kang-ho", "Kim Ki-taek"], ["Choi Woo-shik", "Kim Ki-woo"], ["Park So-dam", "Kim Ki-jung"], ["Cho Yeo-jeong", "Choi Yeon-gyo"]] },
  { id: 438631, title: "Dune", year: 2021, rating: 7.8, votes: 12000, runtime: 155, genres: [878, 12], tagline: "Beyond fear, destiny awaits.", overview: "Paul Atreides travels to the most dangerous planet in the universe to secure his family's future.", cast: [["Timothée Chalamet", "Paul Atreides"], ["Rebecca Ferguson", "Lady Jessica"], ["Oscar Isaac", "Duke Leto"], ["Zendaya", "Chani"]] },
  { id: 862, title: "Toy Story", year: 1995, rating: 8.0, votes: 18000, runtime: 81, genres: [16, 12, 10751, 35], tagline: "The adventure takes off!", overview: "A cowboy doll feels threatened when a flashy space ranger becomes the favourite toy.", cast: [["Tom Hanks", "Woody"], ["Tim Allen", "Buzz Lightyear"], ["Don Rickles", "Mr. Potato Head"]] },
  { id: 238, title: "The Godfather", year: 1972, rating: 8.7, votes: 20000, runtime: 175, genres: [18, 80], tagline: "An offer you can't refuse.", overview: "The ageing head of a crime family hands control of his empire to his reluctant son.", cast: [["Marlon Brando", "Vito Corleone"], ["Al Pacino", "Michael Corleone"], ["James Caan", "Sonny Corleone"], ["Diane Keaton", "Kay Adams"]] },
  { id: 278, title: "The Shawshank Redemption", year: 1994, rating: 8.7, votes: 27000, runtime: 142, genres: [18, 80], tagline: "Fear can hold you prisoner. Hope can set you free.", overview: "A banker sentenced to life in prison builds an unlikely friendship and a quiet plan.", cast: [["Tim Robbins", "Andy Dufresne"], ["Morgan Freeman", "Red"], ["Bob Gunton", "Warden Norton"]] },
  { id: 419430, title: "Get Out", year: 2017, rating: 7.6, votes: 17000, runtime: 104, genres: [9648, 53, 27], tagline: "Just because you're invited, doesn't mean you're welcome.", overview: "A young man's visit to his girlfriend's family estate turns into a nightmare.", cast: [["Daniel Kaluuya", "Chris Washington"], ["Allison Williams", "Rose Armitage"], ["Catherine Keener", "Missy Armitage"]] },
  { id: 244786, title: "Whiplash", year: 2014, rating: 8.4, votes: 15000, runtime: 107, genres: [18, 10402], tagline: "The road to greatness can take you to the edge.", overview: "A young drummer is pushed to breaking point by a ruthless conservatory instructor.", cast: [["Miles Teller", "Andrew Neiman"], ["J.K. Simmons", "Terence Fletcher"], ["Melissa Benoist", "Nicole"]] },
  { id: 313369, title: "La La Land", year: 2016, rating: 7.9, votes: 16500, runtime: 128, genres: [35, 18, 10749, 10402], tagline: "Here's to the fools who dream.", overview: "A jazz pianist and an aspiring actress fall in love while chasing their ambitions in Los Angeles.", cast: [["Ryan Gosling", "Sebastian"], ["Emma Stone", "Mia"], ["John Legend", "Keith"]] },
  { id: 76341, title: "Mad Max: Fury Road", year: 2015, rating: 7.6, votes: 22000, runtime: 121, genres: [28, 12, 878], tagline: "What a lovely day.", overview: "In a desert wasteland, a drifter and a rebel commander flee a tyrant across the sand.", cast: [["Tom Hardy", "Max Rockatansky"], ["Charlize Theron", "Furiosa"], ["Nicholas Hoult", "Nux"]] },
  { id: 546554, title: "Knives Out", year: 2019, rating: 7.8, votes: 12500, runtime: 131, genres: [35, 80, 18, 9648, 53], tagline: "Hell, any of them could have done it.", overview: "A detective investigates the death of a crime novelist whose family all had a motive.", cast: [["Daniel Craig", "Benoit Blanc"], ["Ana de Armas", "Marta Cabrera"], ["Chris Evans", "Ransom Drysdale"], ["Jamie Lee Curtis", "Linda Drysdale"]] },
  { id: 354912, title: "Coco", year: 2017, rating: 8.2, votes: 19000, runtime: 105, genres: [10751, 16, 14, 10402], tagline: "The celebration of a lifetime.", overview: "A boy who dreams of music finds himself in the Land of the Dead on the Day of the Dead.", cast: [["Anthony Gonzalez", "Miguel"], ["Gael García Bernal", "Héctor"], ["Benjamin Bratt", "Ernesto de la Cruz"]] },
  { id: 545611, title: "Everything Everywhere All at Once", year: 2022, rating: 7.8, votes: 6500, runtime: 139, genres: [28, 12, 878, 35], tagline: "The universe is so much bigger than you realize.", overview: "A laundromat owner is swept into a multiverse war where she must connect with other versions of herself.", cast: [["Michelle Yeoh", "Evelyn Wang"], ["Ke Huy Quan", "Waymond Wang"], ["Stephanie Hsu", "Joy Wang"], ["Jamie Lee Curtis", "Deirdre"]] },
  { id: 872585, title: "Oppenheimer", year: 2023, rating: 8.1, votes: 9000, runtime: 181, genres: [18, 36], tagline: "The world forever changes.", overview: "The story of the physicist who led the project that built the atomic bomb, and what it cost him.", cast: [["Cillian Murphy", "J. Robert Oppenheimer"], ["Emily Blunt", "Kitty Oppenheimer"], ["Robert Downey Jr.", "Lewis Strauss"], ["Matt Damon", "Leslie Groves"]] },
  { id: 346698, title: "Barbie", year: 2023, rating: 7.0, votes: 9000, runtime: 114, genres: [35, 12], tagline: "She's everything. He's just Ken.", overview: "Barbie leaves the perfect world of Barbieland and discovers the real one is more complicated.", cast: [["Margot Robbie", "Barbie"], ["Ryan Gosling", "Ken"], ["America Ferrera", "Gloria"]] },
  { id: 493922, title: "Hereditary", year: 2018, rating: 7.3, votes: 7500, runtime: 127, genres: [27, 9648, 53], tagline: "Every family tree hides a secret.", overview: "After the family matriarch dies, her daughter's household starts unravelling in terrifying ways.", cast: [["Toni Collette", "Annie Graham"], ["Alex Wolff", "Peter Graham"], ["Milly Shapiro", "Charlie Graham"], ["Gabriel Byrne", "Steve Graham"]] },
  { id: 120467, title: "The Grand Budapest Hotel", year: 2014, rating: 8.0, votes: 14500, runtime: 100, genres: [35, 18], tagline: "A murder case. A stolen painting. And a legendary concierge.", overview: "A concierge and his lobby boy are caught up in the theft of a priceless painting.", cast: [["Ralph Fiennes", "M. Gustave"], ["Tony Revolori", "Zero Moustafa"], ["Saoirse Ronan", "Agatha"]] },
  { id: 14160, title: "Up", year: 2009, rating: 7.9, votes: 19000, runtime: 96, genres: [16, 35, 10751, 12], tagline: "The greatest adventure is just getting back home.", overview: "A widower ties thousands of balloons to his house and flies to South America, with a stowaway scout.", cast: [["Ed Asner", "Carl Fredricksen"], ["Jordan Nagai", "Russell"], ["Christopher Plummer", "Charles Muntz"]] },
  { id: 8363, title: "Superbad", year: 2007, rating: 7.2, votes: 7500, runtime: 113, genres: [35], tagline: "Come and get some.", overview: "Two inseparable high-schoolers try to score alcohol for a party before they go separate ways.", cast: [["Jonah Hill", "Seth"], ["Michael Cera", "Evan"], ["Christopher Mintz-Plasse", "Fogell"]] },
  { id: 37799, title: "The Social Network", year: 2010, rating: 7.4, votes: 12500, runtime: 121, genres: [18], tagline: "You don't get to 500 million friends without making a few enemies.", overview: "A Harvard student builds a social network and loses friends in the lawsuits that follow.", cast: [["Jesse Eisenberg", "Mark Zuckerberg"], ["Andrew Garfield", "Eduardo Saverin"], ["Justin Timberlake", "Sean Parker"]] },
  { id: 329865, title: "Arrival", year: 2016, rating: 7.6, votes: 18000, runtime: 116, genres: [18, 878, 9648], tagline: "Why are they here?", overview: "A linguist races to communicate with visitors from space before the world goes to war.", cast: [["Amy Adams", "Louise Banks"], ["Jeremy Renner", "Ian Donnelly"], ["Forest Whitaker", "Colonel Weber"]] },
  { id: 335984, title: "Blade Runner 2049", year: 2017, rating: 7.6, votes: 13500, runtime: 164, genres: [878, 18], tagline: "The key to the future is finally unearthed.", overview: "A replicant hunter uncovers a secret that could plunge what's left of society into chaos.", cast: [["Ryan Gosling", "K"], ["Harrison Ford", "Rick Deckard"], ["Ana de Armas", "Joi"], ["Sylvia Hoeks", "Luv"]] },
  { id: 329, title: "Jurassic Park", year: 1993, rating: 7.9, votes: 16000, runtime: 127, genres: [12, 878], tagline: "An adventure 65 million years in the making.", overview: "Visitors to an island theme park of cloned dinosaurs find out what happens when the fences fail.", cast: [["Sam Neill", "Alan Grant"], ["Laura Dern", "Ellie Sattler"], ["Jeff Goldblum", "Ian Malcolm"]] },
  { id: 105, title: "Back to the Future", year: 1985, rating: 8.3, votes: 19500, runtime: 116, genres: [12, 35, 878], tagline: "He's the only kid ever to get into trouble before he was born.", overview: "A teenager is sent 30 years into the past and must make sure his parents fall in love.", cast: [["Michael J. Fox", "Marty McFly"], ["Christopher Lloyd", "Doc Brown"], ["Lea Thompson", "Lorraine Baines"]] },
  { id: 138843, title: "The Conjuring", year: 2013, rating: 7.5, votes: 11000, runtime: 112, genres: [27, 53], tagline: "Based on the true case files of the Warrens.", overview: "Paranormal investigators help a family terrorised by a dark presence in their farmhouse.", cast: [["Vera Farmiga", "Lorraine Warren"], ["Patrick Wilson", "Ed Warren"], ["Lili Taylor", "Carolyn Perron"]] },
  { id: 447332, title: "A Quiet Place", year: 2018, rating: 7.4, votes: 13500, runtime: 91, genres: [27, 18, 878], tagline: "If they hear you, they hunt you.", overview: "A family survives in silence in a world overrun by creatures that hunt by sound.", cast: [["Emily Blunt", "Evelyn Abbott"], ["John Krasinski", "Lee Abbott"], ["Millicent Simmonds", "Regan Abbott"]] },
  { id: 361743, title: "Top Gun: Maverick", year: 2022, rating: 8.2, votes: 9000, runtime: 131, genres: [28, 18], tagline: "Feel the need... The need for speed.", overview: "Maverick returns to train elite pilots for a mission that demands the ultimate sacrifice.", cast: [["Tom Cruise", "Maverick"], ["Miles Teller", "Rooster"], ["Jennifer Connelly", "Penny Benjamin"]] },
  { id: 335787, title: "Uncharted", year: 2022, rating: 7.0, votes: 4700, runtime: 116, genres: [28, 12], tagline: "Fortune favors the bold.", overview: "Street-smart Nathan Drake is recruited to hunt for a fortune lost 500 years ago.", cast: [["Tom Holland", "Nathan Drake"], ["Mark Wahlberg", "Victor Sullivan"], ["Sophia Ali", "Chloe Frazer"]] },
  { id: 597, title: "Titanic", year: 1997, rating: 7.9, votes: 24000, runtime: 194, genres: [18, 10749], tagline: "Nothing on Earth could come between them.", overview: "A young aristocrat falls for a penniless artist aboard the doomed ocean liner.", cast: [["Leonardo DiCaprio", "Jack Dawson"], ["Kate Winslet", "Rose DeWitt Bukater"], ["Billy Zane", "Cal Hockley"]] },
  { id: 1022789, title: "Inside Out 2", year: 2024, rating: 7.6, votes: 4800, runtime: 97, genres: [16, 10751, 12, 35], tagline: "Make room for new emotions.", overview: "Riley's emotions face new arrivals when she becomes a teenager, led by an ambitious Anxiety.", cast: [["Amy Poehler", "Joy"], ["Maya Hawke", "Anxiety"], ["Kensington Tallman", "Riley"]] },
  { id: 693134, title: "Dune: Part Two", year: 2024, rating: 8.2, votes: 5800, runtime: 167, genres: [878, 12], tagline: "Long live the fighters.", overview: "Paul Atreides unites with the Fremen on a path of revenge against those who destroyed his family.", cast: [["Timothée Chalamet", "Paul Atreides"], ["Zendaya", "Chani"], ["Rebecca Ferguson", "Lady Jessica"], ["Austin Butler", "Feyd-Rautha"]] },
  { id: 11, title: "Star Wars", year: 1977, rating: 8.2, votes: 20000, runtime: 121, genres: [12, 28, 878], tagline: "A long time ago in a galaxy far, far away...", overview: "A farm boy joins a smuggler and a princess to take on the Empire's planet-destroying station.", cast: [["Mark Hamill", "Luke Skywalker"], ["Harrison Ford", "Han Solo"], ["Carrie Fisher", "Leia Organa"]] },
  { id: 348, title: "Alien", year: 1979, rating: 8.2, votes: 14500, runtime: 117, genres: [27, 878], tagline: "In space no one can hear you scream.", overview: "The crew of a commercial spaceship answers a distress call and brings back something deadly.", cast: [["Sigourney Weaver", "Ripley"], ["Tom Skerritt", "Dallas"], ["John Hurt", "Kane"]] },
];
